config_name: "Data Diode"
config_version: 1.0
config_date: 06-06-2019

bitrate: 700 # maximum bitrate
#multicast: # comment to disable
#  group: 224.0.2.5

dyode_in:
  #external:
  #  ip: 192.168.1.2 # use for udp-redirect. comment for listen on all ip range (equal to ip 0.0.0.0)
  internal:
    ip: 10.0.1.1
    mac: 00:e0:4c:22:47:76
    interface: enp3s0
dyode_out:
  #external:
  #  ip: 192.168.1.2
  internal:
    ip: 10.0.1.2
    mac: 00:e0:4c:22:47:26
    interface: enp3s0

modules:
  diode_1:
    type: folder
    port: 9700
    bitrate: 100 # in Mb/s
    timeout: 20  # in second
    fec: "4x4"   # forward error correction
    in: /data/diode
    out: /data/diode
    temp: /data/temp
  repository_diode:
    type: folder
    port: 9600
    bitrate: 250
    timeout: 15
    fec: "8x8"
    in: /data/repo
    out: /data/repo
    temp: /data/temp
    delete: no # default yes
      #  ModbusPLC:
      #    type: modbus
      #    ip: 192.168.2.40
      #    registers:
      #      - 30000-30010
      #    coils:
      #      - 00000-00010
      #    port: 9000
      #    port_out: 502
