version: '3.7'

volumes:
  migrate:
    name: migrate
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/hard/migrate_folder

networks:
  vlan1:
    driver: macvlan
    driver_opts:
      parent: enp3s0
    ipam:
      config:
        - subnet: 192.168.1.0/24
  vlan2:
    driver: macvlan
    driver_opts:
      parent: enp3s1
    ipam:
      config:
        - subnet: 192.168.2.0/24

services:
  vmn:
    build: ./machine
    container_name: inputd
    init: true
    privileged: true
    # restart: always
    volumes:
      - migrate:/migrate
    networks:
      vlan1:
        ipv4_address: 192.168.1.10
    environment: 
      - address=/192.168.1.1/infolder
      - user=input
      - password=input
      - type=input
    cap_add:
      - SYS_ADMIN
    logging:
      options:
        max-size: "10m"
        max-file: "20"
  vmo:
    build: ./machine
    container_name: outputd
    init: true
    privileged: true
    # restart: always
    volumes:
      - migrate:/migrate
    networks:
      vlan2:
        ipv4_address: 192.168.2.10
    environment: 
      - address=/192.168.2.1/test
      - user=test
      - password=test
      - type=output
    cap_add:
      - SYS_ADMIN
    logging:
      options:
        max-size: "10m"
        max-file: "10"

