config_name: "Dyode v2"
config_version : 1.0
config_date: 2017-07-25

modules:
  "Automate Modbus 1":
     type: modbus
     port: 9400
     ip: 192.168.0.5
     port_out: 502
     registers:
       - 9-105
     coils:
       - 0-1
